<?php echo $this->doctype(); ?>

<html lang="pt">
    <head>
        <meta charset="utf-8">
        
        
        <?php echo $this->headTitle('DEA -'. $this->translate('Visualização de Análise de Água'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/municipio.js'))
        ; ?>
    <center><img src="/img/banner.png" alt="Sistema de Visualização de Análise de Água"></center>
    <hr align="center" width="1200" size=8 color=black >
    
    </head>
    <body>
        
    
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/gotalogo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Sistema - DEA') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        
                        <?php $partial = ['layout/navigation.phtml', 'default']; ?>
                        <?php $this->navigation('navigation')->menu()->setPartial($partial); ?>
                        <?php echo $this->navigation('navigation')->menu()->render(); ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            
    </form>
            <hr>
            <footer>
                <p>&copy;<?php echo date('Y') ?> by MLDLJ - Universidade Federal de Santa Maria/FW. <?php echo $this->translate('Todos os direitos reservados.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
