<script async defer
        src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>
    
<script type="text/javascript" src="js/cidades.js"></script>

<h1><?php echo $this->translate ('Municípios pertencentes a Bacia do Rio da Várzea') ?></h1>
<center><iframe src="https://www.google.com/maps/d/embed?mid=z_HIhPo9pv1Y.kTVljpIDbZyE" width="1100" height="480"></iframe></center>
