
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

<?php
    require_once 'filtrapocos.php'; 
?>

<script type="text/javascript">var $array_js = '<?php echo $string_array;?>';</script>
<script type="text/javascript" src="js/cidadespocos.js"></script>

<div class="titulo" style="color: #fff">
    <hl><img class='hidden-xs' src="img/mapa.png" alt=""align="left"></hl>
    <center><img class='visible-xs' src='img/mapa.png' width="150" alt="" /></center>
    <center><h1><?php echo $this->translate ('Poços Perfurados na Bacia do Rio da Várzea') ?></h1></center>
    
</div>

<div class="filtro" style="color: #fff"> 
    <fieldset>
        <legend style="color: #fff">Selecione o Filtro desejado: <br></legend>
        <form action=pocoscadastrados method=post id="filtro">
            <div class="col-sm-6">
                <?php echo ('<b>Situação </b><br>');?>
                <div class="col-sm-4">
                    <INPUT TYPE="checkbox" NAME="bombeando" value="Bombeando" onchange="submit()" <?php echo($_POST['bombeando']);?>/> Bombeando<br>
                    <INPUT TYPE="checkbox" NAME="abandonado" VALUE="Abandonado" onchange="submit()" <?php echo($_POST['abandonado']);?>/> Abandonado<br>
                    <INPUT TYPE="checkbox" NAME="nutil" VALUE="Não utilizável" onchange="submit()" <?php echo($_POST['nutil']);?>> Não Utilizável<br>
                    <INPUT TYPE="checkbox" NAME="ninstal" VALUE="Não Instalado" onchange="submit()" <?php echo($_POST['ninstal']);?>> Não Instalado<br>
                </div>
                <div class="col-sm-3">
                    <INPUT TYPE="checkbox" NAME="fechado" VALUE="Fechado" onchange="submit()" <?php echo($_POST['fechado']);?>> Fechado<br>
                    <INPUT TYPE="checkbox" NAME="precario" VALUE="Precário" onchange="submit()" <?php echo($_POST['precario']);?>> Precário<br>
                    <INPUT TYPE="checkbox" NAME="obstruido" VALUE="Obstruído" onchange="submit()" <?php echo($_POST['obstruido']);?>> Obstruído<br>
                    <INPUT TYPE="checkbox" NAME="colmatado" VALUE="Colmatado" onchange="submit()" <?php echo($_POST['colmatado']);?>> Colmatado<br>
                </div>
                <div class="col-sm-3">
                    <INPUT TYPE="checkbox" NAME="parado" VALUE="Parado" onchange="submit()" <?php echo($_POST['parado']);?>> Parado<br>
                    <INPUT TYPE="checkbox" NAME="seco" VALUE="Seco" onchange="submit()" <?php echo($_POST['seco']);?>> Seco<br>
                    <INPUT TYPE="checkbox" NAME="equipado" VALUE="Equipado" onchange="submit()" <?php echo($_POST['equipado']);?>> Equipado<br>
                    <INPUT TYPE="checkbox" NAME="indisp" VALUE="Indisponpível" onchange="submit()" <?php echo($_POST['indisp']);?>> Indisponível<br>
                </div>
            </div>
            <div class="col-sm-6">
                <?php echo ('<b>Qualidade </b><br>');?>
                <div class="col-sm-7">
                    <INPUT TYPE="checkbox" NAME="humano" VALUE="humano" onchange="submit()" <?php echo($_POST['humano']);?>> Consumo Humano<br>
                    <INPUT TYPE="checkbox" NAME="animais" VALUE="animais" onchange="submit()" <?php echo($_POST['animais']);?>> Dessedentação de Animais<br>
                    <INPUT TYPE="checkbox" NAME="irrigacao" VALUE="irrigacao" onchange="submit()" <?php echo($_POST['irrigacao']);?>> Irrigação<br>
                    <INPUT TYPE="checkbox" NAME="recreacao" VALUE="recreacao" onchange="submit()" <?php echo($_POST['recreacao']);?>> Recreação<br>
                </div>
                <div class="col-sm-3">
                    <INPUT TYPE="checkbox" NAME="todos" VALUE="todos" onchange="submit()" <?php echo($_POST['todos']);?>> Todos<br><br>
                    <input type="submit" name="enviar" value="Enviar" style="visibility: hidden"/>
                </div>
            </div>
            

        </form>
    </fieldset>
</div>
<div id="pont">
</div>
<div>

    <p><img width="100%" src="img/legenda.png" alt="Legendas dos poços perfurados"></p>
</div>

<div id="map-canvas" style=" height: 600px; margin-bottom: 20px"></div> 